### ISSUE TITLE
Cloudflare API integrations

### ISSUE THREAD

**Issue by Adel-Magebinary** [TritonDataCenter/triton-cns#21]
Hi guys,

Would be great to have Cloudflare API integration which syncs all zones.

It can be an easy setup for HA.

**Comment by bahamat** [comment]
You can set up CloudFlare as a secondary. See <https://developers.cloudflare.com/dns/zone-setups/zone-transfers/cloudflare-as-secondary/setup/>, with the following caveats.

Skip step 1 "Create TSIG".

For [step 4][1], add the secondary name server IPs as peers using the `cnsadm` command as you would for any other replica peer.

[1]: https://developers.cloudflare.com/dns/zone-setups/zone-transfers/cloudflare-as-secondary/setup/#4-update-registrar
